webstats/waldo/urls.py
from django.conf.urls import url

from . import views

app_name = 'waldo'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^validate/$', views.validate, name='validate'),
    url(r'^game/$', views.game, name='game'),
    url(r'^thanks/$', views.thanks, name='thanks'),
]

webstats/webstats/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^waldo/', include('waldo.urls', namespace="waldo")),
    url(r'^admin/', admin.site.urls),
]

webstats/waldo/models.py
from __future__ import unicode_literals
from django.db import models
from django.utils import timezone
from datetime import timedelta


class player(models.Model):
    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=30)
    gender = models.CharField(max_length=6)
    age = models.IntegerField()
    music_type = models.CharField(max_length=30, default='NA')
    timer = models.CharField(max_length=4, default='NA')
    start_time = models.DateTimeField(default=timezone.now)
    end_time = models.DateTimeField(default=timezone.now)
    duration = models.DurationField(default=timedelta())

    def __str__(self):
        return self.first_name

webstats/waldo/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from django.urls import reverse
from django.utils import timezone
from .models import player

def index(request):
    template = loader.get_template('waldo/index.html')
    context = {
            }
    return HttpResponse(template.render(context, request))

def validate(request):
    template = loader.get_template('waldo/validate.html')

    for key in request.POST:
        if request.POST[key] == '':
            context = {
                    }
            return HttpResponse(template.render(context, request))

    current_player = player()
    current_player.first_name = request.POST['first_name']
    current_player.last_name = request.POST['last_name']
    current_player.gender = request.POST['gender']
    current_player.age = request.POST['age']
    current_player.save()

    # create a session
    request.session['id'] = current_player.id

    return HttpResponseRedirect(reverse('waldo:game'))

def game(request):
    current_player = player.objects.get(pk=request.session['id'])
    current_player.start_time = timezone.now

    template = loader.get_template('waldo/game.html')
    context = {
            }

    return HttpResponse(template.render(context, request))

def thanks(request):
    return HttpResponse("Thank you for playing!")
# Create your views here.

webstats/waldo/templates/waldo/game.html
{% load static %}
<img src="{% static 'waldo/images/puzzle.jpg' %}" width="1200" height="750"
alt="puzzle" usemap="#Waldo">

<map name="Waldo">
        <area shape="rect" coords="200,325,250,375," href="{% url 'waldo:thanks' %}"
        alt="alttext">
</map>

webstats/waldo/templates/waldo/index.html
<h1> Can you find Waldo? </h1>

<p>Instructions here</p>

<form action="{% url 'waldo:validate' %}" method="post">
{% csrf_token %}

        <p>
        <label for="first_name">First Name:</label>
        <input id="first_name" type="text" name="first_name"
        maxlength="20" />
        </p>

        <p>
        <label for="last_name">Last Name:</label>
        <input id="last_name" type="text" name="last_name"
        maxlength="30" />
        </p>

        <p>
        <label for="gender">Gender:</label>
        <input id="gender" type="radio" name="gender" value="M" checked/> Male
        <input type="radio" name="gender" value="F" /> Female
        </p>

        <p>
        <label for="age">Age:</label>
        <input id="age" type="number" name="age" min="0" max="120" />
        </p>
        
        <input type="submit" value="Begin!" />
</form> 

webstats/waldo/templates/waldo/validate.html
<p>Some information was not filled in. Please click the link below
and try entering your information again.</p>

<a href="{% url 'waldo:index' %}">Click here to try again!</a>